# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 812af383d22310795f5f7e60119b74cec507789170635cbac6a5aa25f3fe91ea5cae1cabfcfc2689994cbc054bd8675a2a2af17c23d01cad395da9710201d5a6

test:
  secret_key_base: 09d05f88aa9c509145df7beab716c93aa551c5a36c5162f032b65d8217873a2b80425faa91b7291ed5109f118cb46123720802754a75a12cb563ca1e5d2974ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
